#!/bin/bash

echo 'Beginning run of bootstrap.sh'

pushd provisioners/puppet

# work around Gem SSL issue
# http://railsapps.github.io/openssl-certificate-verify-failed.html
if [ ! -r /root/.gemrc ]; then
  echo ':ssl_verify_mode: 0' >> /root/.gemrc
fi

# configure hiera
if [[ -f './manifests/bootstrap.pp' ]]; then
    puppet apply ./manifests/bootstrap.pp
else
    echo "Hiera deployment manifest not available."
fi

# populate hiera
if [[ -x './scripts/env2yaml.rb' ]] && [[ ! -s '/etc/puppet/hieradata/common.yaml' ]]; then
    ./scripts/env2yaml.rb > /etc/puppet/hieradata/common.yaml
    echo "Exit value: $?"
else
    echo "Hiera population script not available."
fi

# make hiera data available as custom facts
if [[ -r '/etc/puppet/hieradata/common.yaml' ]]; then
  mkdir -p /etc/facter/facts.d
  ln -s /etc/puppet/hieradata/common.yaml /etc/facter/facts.d/common.yaml
  echo "Exit value: $?"
else
    echo "Hiera common data file not available."
fi

# fix the hostname (wtf?)
if [[ -x '/bin/hostname' && -x '/usr/bin/facter' && -x '/usr/bin/puppet' ]]; then
    /bin/hostname $(/usr/bin/facter -p ec2_hostname) && \
        /usr/bin/puppet resource host $(facter -p ec2_hostname) ensure=present ip=$(facter -p ec2_local_ipv4)
else
    echo "Unable to set hostname."
fi

popd

echo 'Completing run of bootstrap.sh'

# vim: set ft=sh
