forge 'forge.puppetlabs.com'

mod "puppetlabs/stdlib"
mod "puppetlabs/firewall"
mod "puppetlabs/mysql"
mod "hunner/hiera"
mod "branan/s3file"
mod "evenup/varnish"
mod "maestrodev/rvm"
mod "thoherr/railsapp"

mod "postfix",
  :git => "https://github.com/huit/evenup-postfix.git",
  :ref => 'mediawiki-poc'
