forge 'forge.puppetlabs.com'

mod "puppetlabs/stdlib"
mod "puppetlabs/concat"
mod "puppetlabs/firewall"
mod "puppetlabs/apache"
mod "puppetlabs/mysql"
mod "hunner/hiera"
mod "branan/s3file"
mod "evenup/varnish"
#mod "maestrodev/rvm"
#mod "thoherr/railsapp"

mod "rvm",
  :git => "https://github.com/huit/puppet-rvm.git",
  :ref => 'home_envvar'

mod "railsapp",
  :git => "https://github.com/huit/puppet-railsapp.git",
  :ref => 'puppetlabs_apache_ownership'

mod "postfix",
  :git => "https://github.com/huit/evenup-postfix.git",
  :ref => 'mediawiki-poc'
